name: Github Actions
on: [push, pull_request]
env:
  PREFERRED_WORKSPACE_MANAGER: yarn # for lage to work property

jobs:

  # lint:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - run: npm ci
  #     - run: npm run lint:packages -- -- -- --quite

  browsers:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: "circleci/node:15.4.0-buster-browsers"
      options: --user 1001
    strategy:
      matrix:
        browser: ["chrome", "firefox"]
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run test-${{matrix.browser}}
        working-directory: packages/__tests__

  router-e2e:
    runs-on: ubuntu-latest
    container:
      image: "circleci/node:16.3.0-buster-browsers"
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
        name: build all packages
      - run: npm run test
        name: run e2e tests
        working-directory: packages/__e2e__